apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: gw-ingress-gw-secret
  namespace: gloo-system
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: Gateway
      namespace: ingress-gw
  to:
    - group: ""
      kind: Secret