apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: api-example-com-route
  namespace: default
  labels:
    app: apis
spec:
  parentRefs:
    - name: https
      namespace: gloo-system
  hostnames:
    - "api.example.com"
  rules:
    - matches:  
      - path:
          type: PathPrefix
          value: /httpbin/
      - path:
          type: PathPrefix
          value: /httpbin2/
      # Can't combine URLRewrite ReplacePrefixMatch filter with 2 matchers: https://github.com/solo-io/gloo/issues/8923
      # - headers:
      #   - name: version
      #     value: v2
      #     type: Exact
      # Referencing a service in another namespace than the Route, so need to add ReferenceGrant to allow this.
      # filters:
      #   - type: URLRewrite
      #     urlRewrite:
      #       path:
      #         type: ReplacePrefixMatch
      #         replacePrefixMatch: /
      backendRefs:
        - name: httpbin
          namespace: httpbin
          port: 8000