apiVersion: v1
kind: Service
metadata:
  name: httpbin-canary
  namespace: httpbin
  labels:
    app: httpbin
    service: httpbin
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 8080
    # targetPort: http
    # protocol: TCP
    # appProtocol: http
  selector:
    app: httpbin