apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: ingress-gw-vho-default-rg
  namespace: default
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: Gateway
      namespace: ingress-gw
  to:
    - group: gateway.solo.io
      kind: VirtualHostOption
    