apiVersion: gateway.solo.io/v1
kind: RouteOption
metadata:
  name: oidc-atv
  namespace: tracks
spec:
  options:
    # prefixRewrite: /
    extauth:
      configRef:
        # references the AuthConfig we defined in oauth-oidc-atv-authconfig.yaml
        name: oauth-oidc-atv-auth
        namespace: default
    # stagedTransformations:
    #   # inheritTransformation: true
    #   # early:
    #   regular:
    #     requestTransforms:
    #     - requestTransformation:
    #         transformationTemplate:
    #           headers:
    #             foo:
    #               text: 'baz'
    #           dynamicMetadataValues:
    #           - metadataNamespace: "org.ddoyle"
    #             key: 'foo'
    #             value:
    #               text: 'bar'
        # - matchers:
        #   - prefix: '/parent'
        #   requestTransformation:
        #     transformationTemplate:
        #       headers:
        #         foo:
        #           text: 'bar'
    # headerManipulation:
    #   # add headers to all responses
    #   responseHeadersToAdd:
    #     - header:
    #         key: "gg-demo-header"
    #         value: "auth-config-demo"
    cors:
      allowOrigin:
        - http://localhost:4000
        - http://127.0.0.1:4000
        - http://portal.example.com
        - http://portal.example.com:8080
      allowHeaders:
        - "Content-Type"
        - "Authorization"
        - "Access-Control-Allow-Origin"
        - "api-key"
      allowMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowCredentials: true