apiVersion: gateway.solo.io/v1
kind: RouteOption
metadata:
  name: policy-filter
  namespace: default
spec:
  options:
    # ddoyle: Wouldn't this clash with the URLRewrite/ReplacePrefixMatch filter in the HTTPRoute?
    # Seems that the K8S Gateway API gets precedence over the configuration here.
    # prefixRewrite: /
    headerManipulation:
      # add headers to all responses
      responseHeadersToAdd:
        - header:
            key: "gg-demo-header"
            value: "prefix-rewrite-demo"